"""Domain schemas — dataclasses, enums, and protocols.

All types here are pure Python (no external dependencies beyond pandas for
DataFrame/Timestamp typing). Pydantic equivalents live in
``backend/api/schemas.py`` and are converted at the API boundary.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Literal, Protocol, TypedDict, runtime_checkable

import pandas as pd

# =============================================================================
# Enums
# =============================================================================


class Market(str, Enum):
    CRYPTO = "crypto"
    KR_STOCK = "kr_stock"


class Interval(str, Enum):
    M1 = "1m"
    M5 = "5m"
    M15 = "15m"
    H1 = "1h"
    H4 = "4h"
    D1 = "1d"


class TrendState(str, Enum):
    UPTREND = "uptrend"          # ADX > threshold + MA aligned ascending
    DOWNTREND = "downtrend"      # ADX > threshold + MA aligned descending
    SIDEWAYS = "sideways"        # ADX <= threshold or MA mixed


class SignalKind(str, Enum):
    GOLDEN_CROSS = "golden_cross"        # MA20 ↑ MA60
    DEATH_CROSS = "death_cross"          # MA20 ↓ MA60
    RSI_OVERBOUGHT = "rsi_overbought"    # RSI 70 상향 진입
    RSI_OVERSOLD = "rsi_oversold"        # RSI 30 하향 진입
    RSI_BULL_DIV = "rsi_bull_div"        # 가격 신저점 + RSI 신저점 미경신
    RSI_BEAR_DIV = "rsi_bear_div"        # 가격 신고점 + RSI 신고점 미경신
    MACD_BULL_CROSS = "macd_bull_cross"  # MACD ↑ Signal
    MACD_BEAR_CROSS = "macd_bear_cross"  # MACD ↓ Signal


class SignalAction(str, Enum):
    BUY = "buy"
    SELL = "sell"
    NEUTRAL = "neutral"


# =============================================================================
# Indicator Configuration
# =============================================================================


class IndicatorConfig(TypedDict, total=False):
    """All keys optional. Defaults applied in ``core.indicators.compute``.

    Note: separate ``ema_periods`` (5/20/60/120) chart overlay is deferred to v2.
    v0.4 uses SMA for chart overlays; EMA(12, 26) is used internally by MACD.
    """

    sma_periods: list[int]              # default [5, 20, 60, 120]
    rsi_period: int                     # default 14
    macd: tuple[int, int, int]          # default (12, 26, 9)
    bbands: tuple[int, float]           # default (20, 2.0)
    adx_length: int                     # default 14


# =============================================================================
# Data Fetching
# =============================================================================


@dataclass(frozen=True)
class FetchRequest:
    """Single OHLCV fetch request."""

    market: Market
    symbol: str
    interval: Interval
    start: pd.Timestamp
    end: pd.Timestamp


# =============================================================================
# Signals
# =============================================================================


@dataclass(frozen=True)
class Signal:
    """A single detected trading signal.

    ``strength`` is fixed at 1.0 in v0.4. Per-kind strength formulas are deferred
    to v2 (see Design §4.3 pseudocode).
    """

    timestamp: pd.Timestamp
    kind: SignalKind
    action: SignalAction
    price: float
    strength: float = 1.0
    detail: dict = field(default_factory=dict)


# =============================================================================
# AI Commentary
# =============================================================================


@dataclass(frozen=True)
class AICommentary:
    """Natural-language explanation of a signal, generated by Groq LLM."""

    signal_kind: SignalKind
    timestamp: pd.Timestamp
    summary: str
    detail: str
    confidence: Literal["low", "medium", "high"]
    model: str
    generated_at: pd.Timestamp
    disclaimer: str = "본 해설은 참고용이며 투자 자문이 아닙니다."


# =============================================================================
# Portfolio
# =============================================================================


@dataclass(frozen=True)
class Holding:
    """A single position in the user's portfolio.

    ``currency`` must be specified explicitly — the analysis layer will not
    guess based on market because users may hold cross-listed instruments.
    """

    market: Market
    symbol: str
    quantity: float
    avg_price: float
    currency: Literal["KRW", "USD", "USDT"]


@dataclass(frozen=True)
class Portfolio:
    holdings: list[Holding]
    base_currency: Literal["KRW", "USD"] = "KRW"


@dataclass(frozen=True)
class FxQuote:
    """Foreign-exchange snapshot used during portfolio valuation.

    Recorded so portfolio analyses are reproducible and auditable.
    """

    pair: str           # e.g. "USDT/KRW", "USD/KRW"
    rate: float
    as_of: pd.Timestamp
    source: str = "FinanceDataReader"


@dataclass(frozen=True)
class SkippedHolding:
    """A holding excluded from aggregate analysis, with the reason recorded."""

    market: Market
    symbol: str
    reason: str


@dataclass(frozen=True)
class HoldingAnalysis:
    """Per-holding analysis result.

    All monetary fields except ``current_price_local`` are expressed in the
    portfolio's ``base_currency``.
    """

    holding: Holding
    current_price_local: float
    current_price: float
    market_value: float
    cost_basis: float
    pnl: float
    pnl_pct: float
    weight: float
    fx_rate: float
    trend: TrendState
    latest_signals: list[Signal]


@dataclass(frozen=True)
class PortfolioAnalysis:
    portfolio: Portfolio
    holdings_analysis: list[HoldingAnalysis]
    total_market_value: float
    total_cost_basis: float
    total_pnl: float
    total_pnl_pct: float
    trend_summary: dict[TrendState, int]
    base_currency: Literal["KRW", "USD"]
    fx_rates: dict[str, FxQuote]
    as_of: pd.Timestamp
    skipped_holdings: list[SkippedHolding] = field(default_factory=list)


# =============================================================================
# Backtesting
# =============================================================================


@dataclass(frozen=True)
class BacktestResult:
    total_return: float          # cumulative return (%)
    annual_return: float         # annualized return (%)
    max_drawdown: float          # MDD (%)
    win_rate: float              # win rate (%)
    sharpe_ratio: float
    num_trades: int
    equity_curve: pd.Series      # index=timestamp, values=equity
    trades: pd.DataFrame         # one row per trade


@runtime_checkable
class Strategy(Protocol):
    """Trading strategy — interface for backtesting.py wrapper.

    Concrete strategies subclass ``backtesting.Strategy`` directly; this
    protocol is for typing only.
    """

    def init(self) -> None: ...

    def next(self) -> None: ...


# =============================================================================
# Auto-trading (v3 placeholder — interface only, never implemented in v0.x)
# =============================================================================


@dataclass(frozen=True)
class OrderRequest:
    market: Market
    symbol: str
    side: Literal["buy", "sell"]
    quantity: float
    order_type: Literal["market", "limit"]
    limit_price: float | None = None


@dataclass(frozen=True)
class OrderResult:
    order_id: str
    status: Literal["pending", "filled", "rejected", "cancelled"]
    filled_quantity: float
    filled_price: float | None
    timestamp: pd.Timestamp


@runtime_checkable
class BrokerProtocol(Protocol):
    """Broker interface — defined now to fix the extension shape, but never
    implemented before v3 (auto-trading). Concrete brokers (KIS, Kiwoom,
    Binance Trade) will arrive in a future PDCA cycle alongside safety
    controls (per-day spend caps, dry-run, kill switch, audit log).
    """

    name: str

    def place_order(self, req: OrderRequest) -> OrderResult: ...

    def cancel_order(self, order_id: str) -> bool: ...

    def get_positions(self) -> list[Holding]: ...

    def get_balance(self, currency: str) -> float: ...


# =============================================================================
# Market Snapshot (TopBar)
# =============================================================================


@dataclass(frozen=True)
class IndexQuote:
    """Single market index value + day change percentage (for TopBar)."""

    value: float
    change_pct: float


@dataclass(frozen=True)
class MarketSnapshot:
    """Aggregated market overview for the TopBar tape."""

    kospi: IndexQuote
    kosdaq: IndexQuote
    usd_krw: IndexQuote
    btc: IndexQuote
    dxy: IndexQuote
    vix: IndexQuote
    timestamp: pd.Timestamp


# =============================================================================
# AI Strategy Coach (v0.5)
# =============================================================================


class OptimizationGoal(str, Enum):
    """User-selected goal driving the AI coach prompt."""

    RETURN = "return"        # cumulative return
    SHARPE = "sharpe"
    MDD = "mdd"              # minimise drawdown
    WIN_RATE = "win_rate"


@dataclass(frozen=True)
class TradingCosts:
    """Per-trade frictional costs in basis points (1 bp = 0.01%).

    Per Design §10 caps: commission/slippage ≤ 100 bp (1%),
    kr_sell_tax ≤ 50 bp (0.5%).
    """

    commission_bps: float = 5.0
    slippage_bps: float = 2.0
    kr_sell_tax_bps: float = 18.0
    apply_kr_tax: bool = True


@dataclass(frozen=True)
class StrategyDef:
    """User-defined trading strategy.

    ``buy_when`` / ``sell_when`` are pandas-eval expressions evaluated against
    a dataframe whose columns include the indicator series. They are validated
    by ``strategy_engine.validate_expression`` before being passed to
    ``pandas.eval`` so arbitrary code execution is impossible.
    """

    name: str
    buy_when: str
    sell_when: str
    holding_max_bars: int | None = None
    indicator_config: IndicatorConfig | None = None
    costs: TradingCosts = field(default_factory=TradingCosts)
    optimization_goal: OptimizationGoal = OptimizationGoal.SHARPE


@dataclass(frozen=True)
class BacktestSplitResult:
    """In-sample + Out-of-sample backtest pair from a single 70/30 split.

    ``oos_result`` may be ``None`` when the OOS slice has too few bars (< 30).
    Per Design §6.4 we degrade gracefully (SkippedHolding pattern) rather than
    raising — the IS result is still useful and ``warnings`` carries context.
    """

    is_result: BacktestResult
    oos_result: BacktestResult | None
    is_period: tuple[pd.Timestamp, pd.Timestamp]
    oos_period: tuple[pd.Timestamp, pd.Timestamp] | None
    is_oos_gap_pct: float | None
    overfit_warning: bool
    costs_applied: TradingCosts
    warnings: list[str] = field(default_factory=list)


# === Built-in indicator catalog ============================================


@dataclass(frozen=True)
class BuiltinIndicator:
    """Metadata for a single indicator exposed to the UI/AI as a building block."""

    name: str                              # human label (e.g. "RSI")
    columns: list[str]                     # df columns it produces
    params: dict                           # default parameters
    description: str                       # one-line Korean description
    category: Literal["momentum", "trend", "volatility", "volume"]


# === AI coach ==============================================================


@dataclass(frozen=True)
class CoachRecommendation:
    """A single boost suggestion returned by the AI coach."""

    indicator: str                         # builtin name or free-form
    params: dict
    role: Literal["filter", "exit_rule", "entry_filter", "sizing"]
    reason: str
    expected_synergy: str
    available: bool                        # True if ``indicator`` matches a builtin
    sample_rule: str | None = None         # expression to AND/OR into buy/sell


@dataclass(frozen=True)
class CoachResponse:
    """Full coach payload — diagnosis + 3 recommendations + warnings."""

    diagnosis: str
    recommendations: list[CoachRecommendation]
    warnings: list[str]
    model: str
    generated_at: pd.Timestamp
    disclaimer: str = "본 추천은 LLM 패턴 매칭 결과로 시장 통찰이 아닙니다."


# === Iteration history =====================================================


@dataclass(frozen=True)
class IterationEntry:
    """A single backtest attempt persisted to parquet for later comparison.

    Stored under ``ITERATION_LOG_DIR/{symbol_safe}_{interval}.parquet``.
    ``iteration_id`` is a full ``uuid4().hex`` (32 chars) — collisions are
    treated as bugs and rejected by ``iteration_log.append``.
    """

    iteration_id: str
    symbol: str
    interval: str
    attempt_no: int
    strategy_def_json: str
    is_total_return: float
    oos_total_return: float | None
    is_sharpe: float
    oos_sharpe: float | None
    is_mdd: float
    oos_mdd: float | None
    is_win_rate: float
    is_oos_gap_pct: float | None
    overfit_warning: bool
    optimization_goal: str
    coach_diagnosis: str | None
    applied_recommendation: str | None
    timestamp: pd.Timestamp
